Add documentation for Scala 3 derivation
pureconfig/pureconfig pull request #1069
Opened 2021-06-07 22:04 UTC by ruippeixotog

As titled.

2021-06-07 22:07 UTC, ruippeixotog commented on docs/docs/docs/scala-3-derivation.md
> +```scala
Unfortunately we can't run any of this through mdoc as our website depends on `pureconfig-generic`, which isn't available in Scala 3. Instead, I ran this on `core/console` and copied the outputs here.

2021-06-08 06:07 UTC, heksesang commented on docs/docs/docs/scala-3-derivation.md
> +After that, you can derive `ConfigReader` instaces for your config class using a `derives` clause:
Missing an n in instances here.

2021-06-08 06:44 UTC, heksesang commented
LGTM, except that one typo I pointed out. :)

2021-06-08 09:46 UTC, jcazevedo requested changes
Other than a small typo, this looks good to me!

2021-06-08 09:46 UTC, jcazevedo commented on docs/docs/docs/scala-3-derivation.md
> +Magnolia-based derivation libaries available in Scala 2 yet so please report any bugs that you find!
```suggestion
Magnolia-based derivation libraries available in Scala 2 yet so please report any bugs that you find!
```

2021-06-08 22:45 UTC, jcazevedo approved these changes
Thanks!

2021-06-08 22:45 UTC, merged