Split README into section files
pureconfig/pureconfig pull request #112
Opened 2017-02-08 00:09 UTC by ruippeixotog

2017-02-08 21:32 UTC, leifwickland approved these changes
It appears to me you faithfully moved all the expected sections to their own pages.

2017-02-08 22:39 UTC, melrief requested changes
The link to overrride behaviour for sealed families is broken, everything else LGTM

2017-02-08 22:39 UTC, melrief commented on core/docs/overrride-behaviour-for-sealed-families.md
> +## Override behaviour for sealed families
Too many `r` in the name of this file :smile:

2017-02-09 20:29 UTC, ruippeixotog commented on core/docs/overrride-behaviour-for-sealed-families.md
> +## Override behaviour for sealed families
Ahah, nice catch! :D Fixed in fee4be3.

2017-02-09 20:30 UTC, melrief approved these changes

2017-02-09 20:30 UTC, merged