Remove dependency on generic for modules' tests
pureconfig/pureconfig pull request #1183
Opened 2021-10-11 23:42 UTC by jcazevedo

This PR aims to reduce the special status pureconfig-generic currently has in the codebase, by removing its dependency from the modules' test scope. This is helpful for #1082.

2021-10-12 22:20 UTC, ruippeixotog requested changes
LGTM overall.

One general suggestion: after seeing 15+ files using this pattern, it seems to be that we should create some test util `def configValueSource(conf: String) = ConfigSource.string(s"""{ key: $conf }""").at("key")` on `BaseSuite` or other central place. In fact, we already have a very similar util for `ConfigValue` and cursors (https://github.com/pureconfig/pureconfig/blob/master/tests/src/test/scala/pureconfig/FluentConfigCursorSuite.scala#L12-L14).

2021-10-12 22:20 UTC, ruippeixotog commented on modules/cats/src/test/scala/pureconfig/module/cats/CatsSuite.scala
> +  case class Numbers[T](numbers: T)
Can we avoid this unnecessary wrapper too? You can use `ConfigSource` here to navigate through a config and extract a `ConfigValue` for `checkReadWrite`, I think. You can also keep two configs `numberListConf` and `numberMapConf` to avoid repetition.

2021-10-12 22:20 UTC, ruippeixotog commented on modules/magnolia/build.sbt
> +  Dependencies.shapeless % Test
Slightly related with this PR: as we are trying to remove the special status of generic, can we remove shapeless from `Dependencies`? Ideally we should be using shapeless only inside generic (here it's ok as we're using it for completely different reasons, just to use utils).

2021-10-12 22:20 UTC, ruippeixotog commented on modules/magnolia/src/test/scala-2.12+/pureconfig/CoproductConvertersSuite2_12.scala
> -import pureconfig.generic.auto._
How was this available here? 😮 I thought `magnolia` didn't depend on `generic`?

2021-10-12 22:20 UTC, ruippeixotog commented on testkit/src/main/scala-2.13-/pureconfig/TypeStringCompat.scala
> +    def typeName = t.runtimeClass.getName.toString
Nit: is it worth changing the type description here to clarify that the type may be erased? (e.g. by appending "erased" or being smarter in case `ClassTag` knows if it's type has type parameters). I'm afraid this might be misleading if it's unclear if errors are using a type tag or class tag.

2021-10-12 22:26 UTC, jcazevedo commented on testkit/src/main/scala-2.13-/pureconfig/TypeStringCompat.scala
> +    def typeName = t.runtimeClass.getName.toString
Is it worth it? Note that this is only used for test descriptions in the `checkRead` and `checkWrite` (and variants) methods.

2021-10-12 22:29 UTC, ruippeixotog commented on testkit/src/main/scala-2.13-/pureconfig/TypeStringCompat.scala
> +    def typeName = t.runtimeClass.getName.toString
Oh, never mind then. I thought it was being used to generate exception messages in library code, I recall that we have similar code working with type/class tags there.

2021-10-12 23:50 UTC, jcazevedo commented on modules/magnolia/build.sbt
> +  Dependencies.shapeless % Test
Sure. That makes sense.

2021-10-12 23:51 UTC, jcazevedo commented on modules/magnolia/src/test/scala-2.12+/pureconfig/CoproductConvertersSuite2_12.scala
> -import pureconfig.generic.auto._
It used the `module` helper, which ended up including generic as a test dependency.

2021-10-12 23:56 UTC, jcazevedo commented on modules/cats/src/test/scala/pureconfig/module/cats/CatsSuite.scala
> +  case class Numbers[T](numbers: T)
> Can we avoid this unnecessary wrapper too?

The problem here is that some of these cats types (`NonEmptySet`, `NonEmptyMap` and `NonEmptyChain`) don't have `TypeTag` nor `ClassTag` instances (see https://github.com/typelevel/cats/issues/2928), so they're not directly usable in `checkReadWrite`. I didn't want to disrupt the rest of the spec much, so I kept the usage of a wrapper here for us to have access to, at least, a `ClassTag` instance.

> You can also keep two configs `numberListConf` and `numberMapConf` to avoid repetition.

I don't mind the repetition much here, and I think it helps with readability given the proximity to the produced values.

2021-10-12 23:57 UTC, jcazevedo commented
> One general suggestion: after seeing 15+ files using this pattern, it seems to be that we should create some test util `def configValueSource(conf: String) = ConfigSource.string(s"""{ key: $conf }""").at("key")` on `BaseSuite` or other central place. In fact, we already have a very similar util for `ConfigValue` and cursors (https://github.com/pureconfig/pureconfig/blob/master/tests/src/test/scala/pureconfig/FluentConfigCursorSuite.scala#L12-L14).

Thanks for this suggestion! I ended up pushing the `conf` method to `BaseSuite`, renaming it to `configValue`, and using it throughout these specs instead of the `ConfigSource`-based loading.

2021-10-13 09:03 UTC, ruippeixotog approved these changes
Thanks @jcazevedo, this will be very useful later!

One nit: now that we define `configValue` like that, it makes me think that we should have a `configValueStr` variant to avoid those awkward `""""` on many definitions. What do you think? Leaving up to you, I accepted this in case you want to do it later.

2021-10-13 11:28 UTC, jcazevedo commented
> One nit: now that we define `configValue` like that, it makes me think that we should have a `configValueStr` variant to avoid those awkward `""""` on many definitions. What do you think? Leaving up to you, I accepted this in case you want to do it later.

Makes sense. I've added a `configString` helper for that.

2021-10-14 14:22 UTC, ruippeixotog approved these changes
Thanks for all the changes!

2021-10-14 14:22 UTC, merged