[WIP] Add location (filename and line number) to errors
pureconfig/pureconfig pull request #139
Opened 2017-02-20 02:12 UTC by jcazevedo

This PR adds the location (filename and line number) to `ConfigReaderFailure`. The location is an `Option` since it might not always be available (we don't always load configurations from a file and some errors can't be pinned to a specific location).

This PR attempts to fix #85.

This is still WIP since I'd like to add more tests and improve the documentation.

2017-02-23 23:42 UTC, jcazevedo commented
I've improved the documentation of the sealed family of `ConfigReaderFailure`s and added a description to the README on how to provide locations to failures.

@melrief and @leifwickland: I think this is ready to be reviewed.

2017-02-24 00:06 UTC, melrief commented
I will review it tomorrow, thanks for the work @jcazevedo !

2017-02-24 02:49 UTC, leifwickland commented on core/docs/error-handling.md
> +PureConfig provides some semantically rich case classes to describe failures
Suggestion: I'd reword this sentence as:

> The `pureconfig.error` package provides semantically rich case classes to describe failures reading from a `ConfigValue`.

Feel free to prefer your wording.

2017-02-24 03:17 UTC, leifwickland commented on core/src/main/scala/pureconfig/error/ConfigReaderFailure.scala
> + * @param filename the complete pathname to the file that contains a given
If the config file is inside of a JAR does this become some useful value like:
`path/to/the.jar#resource/path.conf`?

2017-02-24 03:24 UTC, leifwickland commented on core/src/main/scala/pureconfig/error/ConfigReaderFailure.scala
> +  def description: String = s"(file:$filename: $lineNumber)"
Just a suggestion: 
I think I'd rather this be 
```
s"($filename:$lineNumber)"
```
which seems like a more traditional format for an error report.

2017-02-24 03:28 UTC, leifwickland commented on core/src/main/scala/pureconfig/error/ConfigReaderFailure.scala
> +        Some(ConfigValueLocation(origin.filename, origin.lineNumber - 1))
If ConfigOrigin's line numbering starts at 1 and you're subtracting 1, does that mean you're trying to get zero-based line numbering?
If so I object. I would prefer one-based line numbering.

2017-02-24 03:32 UTC, leifwickland commented on core/src/main/scala/pureconfig/error/ConfigReaderFailure.scala
> + * A failure representing the inability of converting a null value. Since a null
Nitpick: Here and below in a place or two, I'd suggest the phrase "the inability to convert" instead of "the inability of converting".

2017-02-24 03:38 UTC, leifwickland commented on core/src/test/scala/pureconfig/ConfigReaderFailureLocationSuite.scala
> +    val file1 = "conf/error2/a.conf"
Suggestion: Rename the `error2` and `error1` parts of the paths these test files are in to something like `errorLocationReporting` to try to tie them to their purpose.

2017-02-24 03:42 UTC, leifwickland commented on core/src/test/scala/pureconfig/ConfigReaderFailureLocationSuite.scala
> +      Some(ConfigValueLocation(workingDir + file2, 1))))
That seems like it should be line 2, not 1, to me.

2017-02-24 03:44 UTC, leifwickland requested changes
I left a few suggestions.
I'd sure line numbering for error reporting to be one-based.

2017-02-24 15:04 UTC, jcazevedo commented on core/src/main/scala/pureconfig/error/ConfigReaderFailure.scala
> +        Some(ConfigValueLocation(origin.filename, origin.lineNumber - 1))
I agree. I'm not sure what I was thinking. 1-based makes much more sense. I'll fix it later today.

2017-02-24 18:55 UTC, jcazevedo commented on core/docs/error-handling.md
> +PureConfig provides some semantically rich case classes to describe failures
I've reworded it as per your suggestion in 402a1d8.

2017-02-24 18:56 UTC, jcazevedo commented on core/src/main/scala/pureconfig/error/ConfigReaderFailure.scala
> + * @param filename the complete pathname to the file that contains a given
Yes. It will be something like `path/to/the.jar!/path.conf`.

2017-02-24 18:56 UTC, jcazevedo commented on core/src/main/scala/pureconfig/error/ConfigReaderFailure.scala
> +  def description: String = s"(file:$filename: $lineNumber)"
I've modified it in e1f4694. I don't have a strong preference either way, so I'm OK to go with the more traditional format.

2017-02-24 18:57 UTC, jcazevedo commented on core/src/main/scala/pureconfig/error/ConfigReaderFailure.scala
> +        Some(ConfigValueLocation(origin.filename, origin.lineNumber - 1))
Fixed it in a8248b7.

2017-02-24 18:57 UTC, jcazevedo commented on core/src/main/scala/pureconfig/error/ConfigReaderFailure.scala
> + * A failure representing the inability of converting a null value. Since a null
Modified the wording as per your suggestion in 402a1d8.

2017-02-24 18:58 UTC, jcazevedo commented on core/src/test/scala/pureconfig/ConfigReaderFailureLocationSuite.scala
> +    val file1 = "conf/error2/a.conf"
I've scoped the test files used by this suite under the `configFailureLocation` folder in 3c08eb3.

2017-02-24 18:58 UTC, jcazevedo commented on core/src/test/scala/pureconfig/ConfigReaderFailureLocationSuite.scala
> +      Some(ConfigValueLocation(workingDir + file2, 1))))
Yes, you're right. This had to do with the line numbering not being one-based. I've fixed it in a8248b7.

2017-02-24 18:59 UTC, jcazevedo commented
@leifwickland: Thanks for your review. I believe I've addressed all your comments.

2017-02-24 21:43 UTC, leifwickland approved these changes
Awesome work, @jcazevedo! This is a terrific feature.
Thanks for considering my suggestions.

2017-02-24 21:56 UTC, melrief approved these changes
Amazing job @jcazevedo !

2017-02-24 21:56 UTC, melrief commented on core/src/main/scala/pureconfig/error/ConfigReaderFailure.scala
> +sealed abstract class ConfigReaderFailure {
@jcazevedo thanks a lot for adding documentation to the failures!

2017-02-24 21:56 UTC, merged