Generate `Automatic-Module-Name` attribute
pureconfig/pureconfig pull request #1718
Opened 2024-09-25 18:25 UTC by hubertp

It is currently impossible to define `pureconfig` on a module path. This is because Java fails to automatically infer Module name from jar's containing invalid characters (e.g. `_` or `-` in `_2.13` cross version). It's a common problem with Scala artifacts.

This change adds `Automatic-Module-Name` attribute to MANIFEST that contains a valid Java identifier that can be used to define appropriate module dependencies.

2024-10-14 13:39 UTC, hubertp commented
Any problem with this PR? This should unblock anyone who wants to use `pureconfig` as a Java module, with a minimal effort.

2024-10-28 11:53 UTC, grzegorz-bielski commented
This is a nice addition.

cc @ruippeixotog, @jcazevedo

2024-11-08 19:29 UTC, ruippeixotog requested changes
Hey @hubertp, thanks for the contribution. Is there anywhere where I can read more about Java module usages and Scala's recommended approach to this? As you said this seems to be a problem common to all Scala artifacts, so is there general guidance from the Scala team or the community? It seems strange for every project to require that small amount of boilerplate.

This LGTM in general, sending back you just just for minor adjustments.

2024-11-08 19:29 UTC, ruippeixotog commented on build.sbt
> +lazy val javaModuleName = settingKey[String]("Java Module name")
nit: can you please move this to after the projects are defined? This seems to be too niche and minor to be defined at the top of build.sbt.

2024-11-08 19:29 UTC, ruippeixotog commented on build.sbt
> +  .settings(Seq(javaModuleName := s"${name.value.replace("-", ".")}") ++ publishSettingAutomaticModuleName)
I don't understand why we're defining this only for `core` and generic modules. Don't other modules, like `pekko-http` and `scala-xml`, suffer from the same problem? If we can, we should skip the SBT setting boilerplate and just inline this into `commonSettings`.

2025-12-18 16:13 UTC, ruippeixotog commented
Closing due to inactivity. Feel free to reopen this PR or open a new one if you're still looking to work on this.

2025-12-18 16:13 UTC, closed without merging