Make loadConfig return a failure when a namespace doesn't exist
pureconfig/pureconfig pull request #247
Opened 2017-05-27 15:49 UTC by ruippeixotog

Depends on #245 and fixes #218.

2017-05-27 17:30 UTC, derekmorr approved these changes

2017-05-27 18:17 UTC, melrief requested changes
LGTM except the error message that should be more precise

2017-05-27 18:17 UTC, melrief commented on core/src/main/scala/pureconfig/error/ConfigReaderFailure.scala
> +  def description = s"Unable to read file: ${path.toString}"
I would prefer to say why the file is not readable. The message could be `"Unable to read file ${path.toString} because it doesn't exist"`

2017-05-27 18:34 UTC, ruippeixotog commented on core/src/main/scala/pureconfig/error/ConfigReaderFailure.scala
> +  def description = s"Unable to read file: ${path.toString}"
The addition of `CannotReadFile` was already in #245 and there was a discussion [there](https://github.com/pureconfig/pureconfig/pull/245#discussion_r118805343) about this topic. I agree with you, but I think it's a different issue and PR ;)

2017-05-27 18:38 UTC, ruippeixotog commented on core/src/main/scala/pureconfig/error/ConfigReaderFailure.scala
> +  def description = s"Unable to read file: ${path.toString}"
I have just opened #248 for me to deal with this later.

2017-05-28 12:28 UTC, melrief approved these changes

2017-05-28 12:38 UTC, merged