Add a reason to CannotReadFile and catch all read errors
pureconfig/pureconfig pull request #260
Opened 2017-06-04 17:44 UTC by ruippeixotog

This PR improves the handling of file reading errors by preventing `ConfigFactory` from silently ignoring missing files in `parseFile` and dealing with the resulting `ConfigException.IO` exceptions in a special way.

Incidentally, this also makes pureconfig turn all reading IO exceptions into `CannotReadFile` failures, instead of wrapping them into generic `ThrowableFailure` failures as before.

Closes #248.

2017-06-08 13:20 UTC, jcazevedo requested changes
The implementation looks good to me! Thanks for this!

We should also update `ConfigReaderException` to add representation for `CannotReadFile` failures. We previously only had `CannotParse` as a failure without a path, but `CannotReadFile` also falls under that category.

2017-06-08 22:16 UTC, ruippeixotog commented
@jcazevedo you're right, I was not aware that we had special support for `CannotParse`. I generalized the construction of the exception message in cbb5d8b.

2017-06-15 21:56 UTC, jcazevedo approved these changes

2017-06-16 18:25 UTC, melrief approved these changes

2017-06-16 18:25 UTC, melrief commented on core/src/test/scala/pureconfig/ConfigReaderMatchers.scala
> +        inside(left) { case Left(ConfigReaderFailures(failure, Nil)) => pf.valueAt(failure) }
Nice!

2017-06-16 19:48 UTC, merged