Joda time config converters
pureconfig/pureconfig pull request #273
Opened 2017-06-21 21:10 UTC by queimadus

Add `ConfigConvert`ers to `joda-time`'s `Instant`, `Period`, `Interval`, `Duration`, `DateTimeFormatter` and `DateTimeZone`.

Brought to you by [scala-swarm scala hackathon](https://www.scala-swarm.org/), courtesy of @queimadus and @andrebeat.

EDIT: Has the changes from the #268 suggestions.

2017-06-22 14:37 UTC, derekmorr approved these changes

2017-06-22 14:59 UTC, leifwickland requested changes
@queimadus Would you be willing to fix my mistake? Sorry about that. 
You'll have my approval afterward.

2017-06-22 14:59 UTC, leifwickland commented on modules/joda/src/test/scala/pureconfig/module/joda/JodaSpec.scala
> +class JodaSpec extends BaseSuite {
@queimadus Terribly sorry. I remembered the convention in PureConfig incorrectly. This should be renamed to `JodaSuite`. That's entirely my fault.

2017-06-22 23:37 UTC, ruippeixotog reviewed
Other than the minor comment below, LGTM! Thanks for this, @queimadus and @andrebeat.

2017-06-22 23:37 UTC, ruippeixotog commented on modules/joda/src/test/scala/pureconfig/module/joda/JodaSpec.scala
> +  it should "parse Instant" in forAll {
This test and the ones below all test the reading part of the `ConfigConvert`, but not the writing part.

`BaseSuite` provides a convenient `checkArbitrary[A]` method that checks that writing an `A` to a config and reading it back should yield an `A` instance equal to the original one. Consider replacing this whole test by a single `checkArbitrary[Instant]` (same thing with the other types).

2017-06-26 09:22 UTC, queimadus commented on modules/joda/src/test/scala/pureconfig/module/joda/JodaSpec.scala
> +class JodaSpec extends BaseSuite {
Fixed in 92a6a96.

2017-06-26 09:23 UTC, queimadus commented on modules/joda/src/test/scala/pureconfig/module/joda/JodaSpec.scala
> +  it should "parse Instant" in forAll {
I've simplified all `joda` tests with `checkArbitrary` in `92a6a96`.

2017-06-26 10:04 UTC, ruippeixotog approved these changes
LGTM!

2017-06-26 13:09 UTC, leifwickland approved these changes
Thanks, @queimadus and @andrebeat! I really appreciate your contribution and patience.

2017-06-26 13:10 UTC, merged

2017-08-06 21:29 UTC, jcazevedo commented
Thanks for the PR @queimadus and @andrebeat! We would like to add you to the [CONTRIBUTORS](https://github.com/pureconfig/pureconfig/blob/master/CONTRIBUTORS) file. If you agree, please submit another PR in which you add a line with your names, your emails (optional) and your usernames, in line with PRs such as #118, #152 or #160.