Allow reading config values with a namespace to any value with a ConfigReader
pureconfig/pureconfig pull request #275
Opened 2017-06-24 17:35 UTC by ruippeixotog

Replaces the algorithm for loading configs with namespaces as described in #263. It also fixes some bugs:
- `loadConfig` no longer throws exceptions when the namespace does not represent a config object;
- there were some cases where `improveFailures` was not being called after a `ConfigReader` was used. Now all code paths pass through `improveFailures`.

Since we want to navigate through the config one hop at a time, I needed a way to parse the string namespace into a proper path. The process is not straightforward, as Typesafe Config accepts special chars and escape sequences in their paths. It employs internally a [parser](https://github.com/typesafehub/config/blob/master/config/src/main/java/com/typesafe/config/impl/Path.java) with a full fledged [tokenizer](https://github.com/typesafehub/config/blob/master/config/src/main/java/com/typesafe/config/impl/Tokenizer.java), both of which are unfortunately package private. After deliberating a bit, I decided that it would be worth to use the object anyway, as I prefer to rely on their internal code (the library is not updated that much) than to replicate their logic or stop being fully compatible with their paths. Let me know if you disagree with this, any suggestions are welcome!

Closes #263.

2017-06-28 00:08 UTC, jcazevedo requested changes
Looks good to me! The improved test suite should help clarify the behaviour of `loadConfig` with a namespace.

I think you can use [`ConfigUtil`](https://typesafehub.github.io/config/latest/api/com/typesafe/config/ConfigUtil.html) to access the internal parser for namespaces, thus avoiding direct usage of package private code.

2017-06-28 23:14 UTC, ruippeixotog commented
@jcazevedo I didn't know about `ConfigUtil`, great! I changed the wrapper to use it in f8e0a6f (the wrapper is still useful because the Typesafe Config parser doesn't deal with empty lists and path expressions, which I conveniently use to denote the root).

2017-06-29 17:19 UTC, jcazevedo approved these changes
Looks good to me. Thanks for this!

2017-07-05 20:41 UTC, melrief approved these changes
Great PR, in particular the tests are a semi-specification of the different errors that we expect. Thanks for doing this.

2017-07-05 20:41 UTC, melrief commented on CHANGELOG.md
> +  - `ConfigReader` and `ConfigWriter` for `java.math.BigDecimal` and `java.math.BigInteger`.
You are good in writing changelogs 👍

2017-07-05 20:41 UTC, melrief commented on core/src/main/scala/pureconfig/package.scala
> +    // we're not expecting any exception here, this `try` is just for extra safety
Good idea

2017-07-05 23:20 UTC, merged