add tutorial for complex types
pureconfig/pureconfig pull request #291
Opened 2017-07-31 00:40 UTC by melrief

Closes #270.

2017-07-31 01:22 UTC, leifwickland requested changes
Excellent work, @melrief! I've made a few suggestions and tried to correct a few typos.

2017-07-31 01:22 UTC, leifwickland commented on docs/src/main/tut/add-support-for-complex-types.md
> +magic. For instance, it prevents PureConfig from using the `CorpoductHint` as strategy to read
Nitpick: s/CorpoductHint/CoproductHint/

2017-07-31 01:22 UTC, leifwickland commented on docs/src/main/tut/add-support-for-complex-types.md
> +**pros**: The main feature of this method is that it take control over PureConfig on how to
This reads a bit awkwardly to me. It's trying to express something English isn't terribly good at, IMHO. 
I'd suggest 
- "... that PureConfig delegates to it when decoding your configuration"
or
- "... that it supersedes PureConfig to decode your configuration"

If you prefer your wording, then s/take/takes/

2017-07-31 01:22 UTC, leifwickland commented on docs/src/main/tut/add-support-for-complex-types.md
> +as blackbox and applies it when it has to read your configuration
Nitpick: "as *a* blackbox"

2017-07-31 01:22 UTC, leifwickland commented on docs/src/main/tut/add-support-for-complex-types.md
> +PureConfig works out-of-the-box with Scala sealed familes of case classes and one simple solution
Suggestion: I'd either break this into two sentences or reword it like "Because PureConfig ... classes, one simple ..."

2017-07-31 01:22 UTC, leifwickland commented on docs/src/main/tut/add-support-for-complex-types.md
> +This method consists in adding the generic representation for the configuration.
Nitpick: s/in/of/

2017-07-31 01:22 UTC, leifwickland commented on docs/src/main/tut/add-support-for-complex-types.md
> +2. For each field in the generic representation, if there is a default value for that field or not.
Suggestion:
"Whether each field in the generic representation has a default value."

2017-07-31 01:22 UTC, leifwickland commented on docs/src/main/tut/add-support-for-complex-types.md
> +each one with pros and cons. While there is a preferable method, we will
I'd be tempted to add a direct link to the preferred method. This paragraph conveys more of an air of mystery than developers are generally expecting when scanning documentation for how to get poop done.

2017-07-31 01:22 UTC, leifwickland commented on docs/src/main/tut/add-support-for-simple-types.md
> +Let's see how to support the type
Do you think there should be any exposition here for why the type isn't supported? My concern is that someone might land here expecting they need to follow these steps in order to get a `case class` working. 

Perhaps something like: Out of the box, PureConfig supports `case class`es, but not regular classes. Let's see how to support a simple class with a single mutable field.

2017-08-03 22:46 UTC, ruippeixotog reviewed
As I already said in #265, this tutorial is very nice, @melrief! Thank you for taking the time to add it here.

The content seems good to me, I have nothing to point out. All comments below are English mistakes/nitpicks I found, not serious problems. As I'm not a native English speaker either I may need some corrections myself :)

Some general writing style suggestions:
- Can you make sure that every phrase before a code block or listing ends with `:` and every list item terminates with `;` except the last, which should end with `.`?
- shapeless is always written with lowercase in their README. Can you change them here? (I think we already pointed that out when writing the [FAQ](https://github.com/pureconfig/pureconfig/blob/master/docs/faq.md)).

2017-08-03 22:46 UTC, ruippeixotog commented on docs/src/main/tut/add-support-for-complex-types.md
> +**cons**: The main feature of this method is also the drawback, because by taking control over
I think you need to add an extra space between pros and cons; otherwise they will be rendered without a newline separating them.

Also, s/the drawback/its drawback/

2017-08-03 22:46 UTC, ruippeixotog commented on docs/src/main/tut/add-support-for-complex-types.md
> +each one with pros and cons. While there is a preferable method, we will
I agree. On the same basis, I would also present the preferred solution first and the two alternatives afterwards.

I also think "preferred" is a better word in that context, instead of "preferable".

2017-08-03 22:46 UTC, ruippeixotog commented on docs/src/main/tut/add-support-for-complex-types.md
> +- **method 1** is good to add support for simple types or types that don't need PureConfig's way to decode products (classes) or coproducts (sealed families of classes)
By "products (classes)", it should be read "products (case classes)".

2017-08-03 22:46 UTC, ruippeixotog commented on docs/src/main/tut/add-support-for-complex-types.md
> +Support for more complex types, such as Java configurations, can be achieved in many different methods,
s/achieved in/achieved with/

2017-08-03 22:46 UTC, ruippeixotog commented on docs/src/main/tut/add-support-for-complex-types.md
> +Similarly to add support for simple types, it is possible to manually create a
s/to add/to adding/, I think.

2017-08-03 22:46 UTC, ruippeixotog commented on docs/src/main/tut/add-support-for-complex-types.md
> +`Identifiable`. This is, generally speaking, not a good idea. In theory you want PureConfig
Consider replacing "In theory" with "In most cases".

2017-08-03 22:46 UTC, ruippeixotog commented on docs/src/main/tut/add-support-for-complex-types.md
> +needed from the configuration and then map it to the original complex type. Note that this
s/map it/maps it/

2017-08-03 22:46 UTC, ruippeixotog commented on docs/src/main/tut/add-support-for-complex-types.md
> +method follows what you usually do in other libraries (e.g. Circe) to support new datatypes and
s/datatypes/data types/

2017-08-03 22:46 UTC, ruippeixotog commented on docs/src/main/tut/add-support-for-complex-types.md
> +**cons**: this method needs to duplicate the configuration and PureConfig needs to do two
Consider "needs the configuration to be duplicated" instead.

2017-08-03 22:46 UTC, ruippeixotog commented on docs/src/main/tut/add-support-for-complex-types.md
> +PureConfig is based on Shapeless Generics which is used to represent data structures in a
s/which is/which are/

2017-08-03 22:46 UTC, ruippeixotog commented on docs/src/main/tut/add-support-for-complex-types.md
> +has a Generic instance provided by Shapeless while `Identifiable` doesn't.
Shouldn't Generic be `Generic` instead?

2017-08-03 22:46 UTC, ruippeixotog commented on docs/src/main/tut/add-support-for-complex-types.md
> +After we added this, PureConfig is able to load `Class1` and `Class2` from configuration.
s/added/add/

2017-08-03 22:46 UTC, ruippeixotog commented on docs/src/main/tut/add-support-for-complex-types.md
> +as sealed family of `Class1` and `Class2`, or coproduct of them if you want:
s/as sealed/as a sealed/

2017-08-03 22:46 UTC, ruippeixotog commented on docs/src/main/tut/add-support-for-complex-types.md
> +supported by the library and "map it" to your new data type.
I think "to the new data type" is better here.

2017-08-03 22:46 UTC, ruippeixotog commented on docs/src/main/tut/add-support-for-simple-types.md
> +If you want to define both operations, the easier way to add full support for a class is by creating a `ConfigConvert`:
s/easier/easiest/

2017-08-06 12:32 UTC, melrief commented
@leifwickland @ruippeixotog thanks for the comments! I think I've fixed all the comments but please have another look if you can.

2017-08-06 17:11 UTC, ruippeixotog commented on docs/src/main/tut/add-support-for-complex-types.md
> +Because PureConfig is based on Shapeless and Shapeless doesn't support non-case classes and interfaces,
This phrase still has occurrences of "Shapeless".

2017-08-06 17:11 UTC, ruippeixotog commented on docs/src/main/tut/add-support-for-complex-types.md
> +Because  PureConfig works out-of-the-box with Scala sealed familes of case classes, one simple solution
There's an extra space here.

2017-08-06 17:11 UTC, ruippeixotog commented on docs/src/main/tut/add-support-for-complex-types.md
> +to support unsupported complex types is to
Missing a `:` here.

2017-08-06 17:11 UTC, ruippeixotog commented on docs/src/main/tut/add-support-for-complex-types.md
> +needed from the configuration and then map it to the original complex type. Note that this
You forgot to handle this one.

2017-08-06 18:07 UTC, melrief commented
@leifwickland @ruippeixotog better? Please ignore the commit messages, I'll squash this before merging because it should be only one single commit.

2017-08-06 21:44 UTC, ruippeixotog approved these changes
LGTM! Thanks for addressing all those pedantic comments :)

2017-08-06 22:19 UTC, melrief commented
@ruippeixotog thanks for making all those pedantic comments :)

2017-08-07 16:16 UTC, leifwickland approved these changes
LGTM. 👍 
One more nitpick.

2017-08-07 16:16 UTC, leifwickland commented on docs/src/main/tut/add-support-for-complex-types.md
> +The example is composed by one interface and two implementations:
Nitpick: typically "composed of" not "composed by"

2017-08-07 19:12 UTC, melrief commented on docs/src/main/tut/add-support-for-complex-types.md
> +The example is composed by one interface and two implementations:
Fixed

2017-08-13 15:36 UTC, jcazevedo requested changes
I just left a minor nitpick. This is a great tutorial!

2017-08-13 15:36 UTC, jcazevedo commented on docs/add-support-for-complex-types.md
> +Point 2. is trivial because both `Class1` and `Class2` don't have default values for fields:
There's an extra period after `Point 2`.

2017-08-15 00:06 UTC, jcazevedo approved these changes

2017-08-16 20:21 UTC, merged