Add support of NonEmptySet into the cat's module.
pureconfig/pureconfig pull request #393
Opened 2018-07-16 16:35 UTC by NicolaeNMV

Cats 1.1.0 added the support of NonEmptySet. Add the pureconfig convertors to support it.

2018-07-16 17:09 UTC, ruippeixotog requested changes
Thanks for your PR, @NicolaeNMV, looks good!

Can you just add tests for the `NonEmptySet` writer you wrote, so that Coveralls doesn't complain? It would also be awesome if you added writer tests for the other non-empty data structures :)

2018-07-17 11:15 UTC, NicolaeNMV commented
@ruippeixotog thanks for reviewing this so quickly ;)

I've added the missing tests plus did some refactoring to make the tests easier to read.

2018-07-17 14:07 UTC, ruippeixotog approved these changes
LGTM! Thanks again!

2018-07-17 15:47 UTC, leifwickland commented on modules/cats/src/main/scala/pureconfig/module/cats/package.scala
> +  implicit def nonEmptySetReader[T](implicit listReader: ConfigReader[SortedSet[T]]): ConfigReader[NonEmptySet[T]] =
Nitpick: `listReader` is slightly misnamed. It's probably better called a `setReader`. Ditto on 39.

2018-07-17 15:49 UTC, leifwickland approved these changes
Thanks for this nice addition, @NicolaeNMV, and for improving the test coverage.

I sent along a trivial suggestion.

Approved either way.

2018-07-17 16:59 UTC, NicolaeNMV commented
@leifwickland I've slightly changed the naming of the vals to avoid repetition of the information that is in the type. I also made a better use of new lines to group the reader and the writer together. Can revert if that's too much. WDYT ?

2018-07-17 17:01 UTC, leifwickland commented
@NicolaeNMV That's even better than what I suggested. Thank you.

2018-07-17 17:04 UTC, merged

2018-07-17 17:08 UTC, leifwickland commented
@NicolaeNMV Thanks again for the contribution. Would you like to send a PR to add yourself to the [pureconfig contributors list](https://github.com/pureconfig/pureconfig/blob/6b6e0ffb118f1b80fa2254c0ddc4679cdfdc4837/CONTRIBUTORS)?