Generalize AllowMissingKeys behavior to writers
pureconfig/pureconfig pull request #418
Opened 2018-09-29 16:27 UTC by ruippeixotog

Currently, we have a pluggable system for readers that can handle missing (undefined) keys. On the writing side we currently aren't doing the same, and instead we statically check if writers are instances of `OptionConfigWriter` (a private internal class).

This PR renames `AllowMissingKeys` to `ReadsMissingKeys` and creates a new `WritesMissingKeys` trait that provides the mechanisms to allow any custom type to have option-like semantics on write.

2018-09-29 23:18 UTC, jcazevedo requested changes
Looks good! I just left comments in some typos in the documentation.

Even though the behavior of these traits is tested in the specs that test the derivation logic, I think it's a good idea to add an explicit test for the `WritesMissingKeys` trait, using a custom `ConfigWriter`.

2018-09-29 23:18 UTC, jcazevedo commented on core/src/main/scala/pureconfig/CollectionReaders.scala
> + * failure when one or more of them are missing. Mixing in this trait into the key's `ConfigReader` signals that a
I think there's an `if` missing: `Mixing in this trait into the key's `ConfigReader` signals that if a value is missing...`.

2018-09-29 23:18 UTC, jcazevedo commented on core/src/main/scala/pureconfig/CollectionReaders.scala
> + * value is missing for the key, the `ConfigReader` can be called with an cursor in the "undefined" state.
Replace `an cursor` with `a cursor`.

2018-09-29 23:18 UTC, jcazevedo commented on core/src/main/scala/pureconfig/CollectionWriters.scala
> + * method that parent writers and use in order to decide whether or not they should write a value using this writer.
Replace `writers and use` by `writers can use`.

2018-09-30 22:13 UTC, ruippeixotog commented
@jcazevedo I must have been half-asleep when I wrote those comments 😅 Everything should be fine now, and I also added the test you requested.

2018-10-01 00:19 UTC, jcazevedo approved these changes
Looks good to me!

2018-10-03 22:44 UTC, merged