FluentConfigCursor
pureconfig/pureconfig pull request #443
Opened 2018-12-22 22:46 UTC by ruippeixotog

Creates a `FluentConfigCursor`, a version of `ConfigCursor` with a more fluent interface, focused on config navigation instead of error handling. This is optimized for cases where we want to easily navigate through deep structures and we don't want to worry about doing for-comprehensions or handling `Either` valued each step of the way.

Even though I have a preference for this kind of API, I added this as an alternative for the existing cursors so that we don't break existing code. With time, we can choose to change the default cursor and eventually deprecate and delete the old API. The new API can easily be used by calling `.fluent` on an existing cursor, so it should still be very convenient.

I didn't update the documentation this time. I'll do it later, before we release the next version :)

Depends on #442.

2019-01-18 23:05 UTC, jcazevedo requested changes
This looks very good! Thanks, @ruippeixotog!

2019-01-18 23:05 UTC, jcazevedo commented on core/src/main/scala/pureconfig/FluentConfigCursor.scala
> +  def mapList[A](f: ConfigCursor => ConfigReader.Result[A]) =
Just for consistency with the other public methods in this class:

```suggestion
  def mapList[A](f: ConfigCursor => ConfigReader.Result[A]): ConfigReader.Result[List[A]] =
```

2019-01-18 23:05 UTC, jcazevedo commented on modules/yaml/src/main/scala/pureconfig/module/yaml/package.scala
> +        ConfigReader.Result.sequence[(String, AnyRef), mutable.Iterable](entries).right.map(_.toMap.asJava)
In Scala 2.11, `Either` doesn't extend `Product` nor `Serializable`, so the type of `entries` is inferred as `Product with Serializable with Either[ConfigReaderFailures, (String, AnyRef)]`. Since `mutable.Iterable[A]` is invariant in type `A`, this fails to compile. I think we can either explicitly type the `sequence` method in `Iterable` instead (which is covariant in type `A`) or explicitly type the `entries` variable as `mutable.Iterable[ConfigReader.Result[(String, AnyRef)]]`.

2019-01-26 15:44 UTC, ruippeixotog commented
@jcazevedo @leifwickland can you please take another look at this?

2019-01-28 15:50 UTC, jcazevedo approved these changes
Sorry for the slow turnaround time. Looks good!

2019-01-28 18:52 UTC, merged