Additional scalaz data structures
pureconfig/pureconfig pull request #462
Opened 2019-04-17 02:45 UTC by ChernikovP

Attempt to add `DList`, `Dequeue` and `Heap` data structures to `scalaz` module.

2019-04-17 03:18 UTC, ChernikovP commented
CI failed due to `README` diff:

```
-// res0: pureconfig.ConfigReader.Result[ScalazConfig] = Right(ScalazConfig(scalaz.DList@284be06d,FullDequeue(OneAnd(1,[]),1,OneAnd(3,[2]),2),[1,2,3],<heap>,Bin(2,Bin(1,Tip(),Tip()),Bin(3,Tip(),Tip())),Just(1),NonEmpty[1,2,3],Bin(three,3,Bin(one,1,Tip,Tip),Bin(two,2,Tip,Tip))))
+// res0: pureconfig.ConfigReader.Result[ScalazConfig] = Right(ScalazConfig(scalaz.DList@53409a9b,FullDequeue(OneAnd(1,[]),1,OneAnd(3,[2]),2),[1,2,3],<heap>,Bin(2,Bin(1,Tip(),Tip()),Bin(3,Tip(),Tip())),Just(1),NonEmpty[1,2,3],Bin(three,3,Bin(one,1,Tip,Tip),Bin(two,2,Tip,Tip))))
```

Unfortunately, this is because `DList` is not a case class and hasn't  overridden `toString` method.

I'm not sure whether it makes sense to modify `.travis.yml` to have `git diff --exit-code ':(exclude)modules/scalaz/README.md';` instead of `git diff --exit-code;`, but otherwise every subsequent build will fail.

2019-04-17 22:07 UTC, ruippeixotog requested changes
Thanks for adding this, @ChernikovP!

2019-04-17 22:07 UTC, ruippeixotog commented on modules/scalaz/src/test/scala/pureconfig/module/scalaz/equality/package.scala
> +  implicit def dListEquality[A]: Equality[DList[A]] = new Equality[DList[A]] {
Can you add a quick comment here and in the instance below explaining why you need to override the default equality?

2019-04-17 22:07 UTC, ruippeixotog commented on modules/scalaz/src/main/tut/README.md
> +  number-dlist: [1,2,3],
Regarding your error, I'd actually leave a single list-like structure here and delete the others. There is little value in showing all the data structures we support if the mechanism to encode and read them is always the same.

2019-04-19 00:43 UTC, leifwickland approved these changes
I approve in general and leave getting the specifics right to @ruippeixotog.

Thanks for the contribution, @ChernikovP!

2025-12-18 16:12 UTC, ruippeixotog commented
Closing due to inactivity. Feel free to reopen this PR or open a new one if you're still looking to work on this.

2025-12-18 16:12 UTC, closed without merging