Add website section for ConfigSource
pureconfig/pureconfig pull request #563
Opened 2019-09-07 16:35 UTC by ruippeixotog

Depends on #562.

2019-09-08 22:01 UTC, jcazevedo requested changes
There are some other pages in the website docs that we should update:

* There are mentions to `loadConfig*` methods in the ["Quick Start"](https://github.com/pureconfig/pureconfig/blob/56de256ec1bfd28245c0a1000ff28bb7cc91f616/docs/src/main/tut/docs/index.md) page. Now that we have a whole section on loading configs, we can point users there for more details. It also adds some continuity to the documentation.
* The ["Supporting New Types"](https://github.com/pureconfig/pureconfig/blob/56de256ec1bfd28245c0a1000ff28bb7cc91f616/docs/src/main/tut/docs/supporting-new-types.md) page mentions `loadConfig` before a code block that uses `load` on a `ConfigSource`.
* The ["Error Handling"](https://github.com/pureconfig/pureconfig/blob/56de256ec1bfd28245c0a1000ff28bb7cc91f616/docs/src/main/tut/docs/error-handling.md) page mentions `loadConfig` and `loadConfigOrThrow` before a code block that showcases `loadOrThrow`.
* The ["Non-Automatic Derivation"](https://github.com/pureconfig/pureconfig/blob/56de256ec1bfd28245c0a1000ff28bb7cc91f616/docs/src/main/tut/docs/non-automatic-derivation.md) page mentions `loadConfig` before a code block that uses `load` on `ConfigSource`.

2019-09-08 22:01 UTC, jcazevedo commented on docs/src/main/tut/docs/loading-a-config.md
> +In the Quick Start section we used `ConfigSource.default.load[MyClass]` to read a config from an `application.conf`
Can we add a link to the Quick Start section here?

2019-09-08 22:01 UTC, jcazevedo commented on docs/src/main/tut/docs/loading-a-config.md
> +After you have a config source you can read your config using several methods:
Since we already used `read` before with a slightly different meaning, I think that changing this to `load` makes things clearer:

```suggestion
After you have a config source you can load your config using several methods:
```

2019-09-08 22:01 UTC, jcazevedo commented on docs/src/main/tut/docs/loading-a-config.md
> +otherAppSource.recoverWith { case _ => appSource }.load[Conf]
I prefer using a successful scenario here. We can show more usages of `recoverWith`, but I think it's clearer if the first one is a successful case.

```suggestion
otherAppSource.recoverWith { case _ => defaultsSource }.load[Conf]
```

2019-09-09 02:36 UTC, ruippeixotog commented on docs/src/main/tut/docs/loading-a-config.md
> +After you have a config source you can read your config using several methods:
Sure. I tried to distinguish the two actions as you said, but this one must have slipped.

2019-09-09 02:38 UTC, ruippeixotog commented on docs/src/main/tut/docs/loading-a-config.md
> +otherAppSource.recoverWith { case _ => appSource }.load[Conf]
I intended it to be a successful scenario, but I actually didn't notice the error. Thanks!

2019-09-09 09:46 UTC, jcazevedo approved these changes
Looks great! Thanks for this!

2019-09-09 21:02 UTC, merged