change ConfigValueLocation to be able to represent more locations
pureconfig/pureconfig pull request #733
Opened 2020-04-04 01:42 UTC by mberndt123

Hey,

I've noticed that pureconfig doesn't report error locations properly for configurations that were parsed from Strings. When [parsing a String](https://lightbend.github.io/config/latest/api/com/typesafe/config/ConfigFactory.html#parseString-java.lang.String-com.typesafe.config.ConfigParseOptions-) with the Typesafe Config library, it's possible to pass a `ConfigParseOptions` object, and that object may contain a textual description of the origin set with [`setOriginDescription`](https://lightbend.github.io/config/latest/api/com/typesafe/config/ConfigParseOptions.html#setOriginDescription-java.lang.String-). That string should show up somewhere in configuration error messages, but the current implementation in pureconfig only considers URLs when creating a `ConfigValueLocation` from a `ConfigOrigin`, so it will not work for this case.

I therefore think that the only sane solution is to give up on the idea that a `ConfigValueLocation` is a pair of URL and line number and just treat it as a glorified string. Calling `description` on a `ConfigOrigin` object even appends the line number if available, so we don't even need to worry about that anymore.
Also `java.net.URL` is completely insane anyway, e. g. it does a DNS lookup in its `equals` and `hashCode` methods, so it should probably never be used.

2020-04-04 04:29 UTC, mberndt123 commented
OK, CI seems to be failing because of documentation. Any hints on how to fix that?

2020-04-04 12:01 UTC, jcazevedo commented
> OK, CI seems to be failing because of documentation. Any hints on how to fix that?

The CI is failing because the output of the PureConfig's site changed. The check is there to catch unintended changes. It's OK to fail that check if the changes are intended, as it seems to be the case.

2020-04-04 12:20 UTC, mberndt123 commented
Yes it is indeed intentional. This is an API/ABI change, and so it may break users' code. If you think it's necessary, it's probably possible to find a way to implement this that doesn't break the ABI. Let me know what you think…

2020-04-04 12:24 UTC, mberndt123 commented
Yes, this is a breaking change… I'd love to implement it without breaking users, but the way things stand, the URL is a non-optional field of the `ConfigValueLocation` class, and the whole point here is to allow `ConfigValueLocation`s that don't have that field.

2020-04-06 23:49 UTC, mberndt123 commented
@ruippeixotog , can you provide any feedback on this idea?

I've thought about this a bit more and right now I can't think of any reason why `ConfigValueLocation` would be needed at all, because we can simply use Typesafe Config's `ConfigOrigin` class instead. The library is tightly coupled to Typesafe Config one way or the other, and as every programmer knows, the best kind of code is the code you delete…

2020-04-08 17:41 UTC, ruippeixotog commented
@mberndt123 thanks for the PR! I'll take a look at this on the weekend.

2020-04-08 18:02 UTC, mberndt123 commented
Great, looking forward for your comments!

2020-04-10 14:24 UTC, jcazevedo requested changes
@mberndt123: Thanks for the PR!

I'm OK with using `ConfigOrigin` instead of `ConfigValueLocation`. However, I don't think we should assume that all cursors and all failures have an origin.

I'd also prefer renaming mentions of "location" to "origin", for consistency.

2020-04-10 14:24 UTC, jcazevedo commented on tests/src/main/scala/pureconfig/ConfigReaderMatchers.scala
> +  val hardcodedValueLocation = ConfigOriginFactory.newSimple("hardcoded value")
Can you add a comment here explaining where this comes from? It took me a while to figure out that this was what Typesafe Config was using for hardcoded values.

2020-04-10 14:24 UTC, jcazevedo commented on core/src/main/scala/pureconfig/ConfigCursor.scala
> +  def location: ConfigOrigin = if (isUndefined) ConfigOriginFactory.newSimple() else value.origin()
I think this should still be an `Option`. I don't think that a cursor pointing to an undefined value should have an origin.

2020-04-10 14:24 UTC, jcazevedo commented on core/src/main/scala/pureconfig/error/ConfigReaderFailure.scala
> +  def location: ConfigOrigin
I think this should be an `Option`. We have failures that we can't relate to a given origin (the `CannotRead` ones, for example).

2020-04-10 14:24 UTC, jcazevedo commented on modules/yaml/src/main/scala/pureconfig/module/yaml/YamlConfigSource.scala
> +  private[this] def toConfigValueLocation(path: URL, mark: Mark): ConfigOrigin = {
This should be renamed to `toConfigOrigin`.

2020-04-10 14:24 UTC, jcazevedo commented on tests/src/main/scala/pureconfig/ConfigReaderMatchers.scala
> +  val string1ValueLocation = stringValueLocation(1)
Can you also add a comment to this explaining its uses?

2020-04-10 14:24 UTC, jcazevedo commented on tests/src/test/scala/pureconfig/ConfigReaderExceptionSuite.scala
> +    fail1 match {
Can we also use `inside` for this?

2020-04-10 14:24 UTC, jcazevedo commented on tests/src/test/scala/pureconfig/ConfigReaderExceptionSuite.scala
> +    val location = s"$file @ file:$workingDir$file"
This is now unused.

2020-04-11 01:06 UTC, mberndt123 commented on tests/src/main/scala/pureconfig/ConfigReaderMatchers.scala
> +  val hardcodedValueLocation = ConfigOriginFactory.newSimple("hardcoded value")
I now removed this and replaced it with this:
```
val emptyConfigOrigin: Option[ConfigOrigin] = Some(ConfigOriginFactory.newSimple())
```
I think that makes it sufficiently obvious that this is a default value.

2020-04-11 01:07 UTC, mberndt123 commented on core/src/main/scala/pureconfig/ConfigCursor.scala
> +  def location: ConfigOrigin = if (isUndefined) ConfigOriginFactory.newSimple() else value.origin()
OK.

2020-04-11 01:09 UTC, mberndt123 commented on core/src/main/scala/pureconfig/error/ConfigReaderFailure.scala
> +  def location: ConfigOrigin
OK

2020-04-11 01:09 UTC, mberndt123 commented on modules/yaml/src/main/scala/pureconfig/module/yaml/YamlConfigSource.scala
> +  private[this] def toConfigValueLocation(path: URL, mark: Mark): ConfigOrigin = {
OK

2020-04-11 01:10 UTC, mberndt123 commented on tests/src/main/scala/pureconfig/ConfigReaderMatchers.scala
> +  val string1ValueLocation = stringValueLocation(1)
I've removed it, because `stringValueLocation(1)` is almost as easy to type.

2020-04-11 01:12 UTC, mberndt123 commented on tests/src/test/scala/pureconfig/ConfigReaderExceptionSuite.scala
> +    fail1 match {
Yes. The reason I hadn't done that in the first place was that `inside` uses a type parameter called `A1`, and there's a `case class` defined in the file that is also called `A1`, and that caused a compiler error message. I've now renamed the case class to `AA1`.

2020-04-11 01:13 UTC, mberndt123 commented on tests/src/test/scala/pureconfig/ConfigReaderExceptionSuite.scala
> +    val location = s"$file @ file:$workingDir$file"
It is also now gone.

2020-04-11 01:16 UTC, mberndt123 commented
I think I have addressed your comments, let me know what you think. Btw, the diffstat is now -313+313 :smiley:

2020-04-24 21:18 UTC, mberndt123 commented
Hey @jcazevedo ,

Do you think you might get around to reviewing this over the next couple of days?

2020-05-22 09:40 UTC, mberndt123 commented
Hey @jcazevedo and @ruippeixotog,

I would still like to get this merged, is there anything I can do to make this happen?

I've now updated the branch to the latest master, so there are no more conflicts.

2020-05-22 10:52 UTC, mberndt123 commented
Any idea why the CI job fails on 2.13? It works on my machine :man_shrugging:

2020-05-23 15:56 UTC, ruippeixotog approved these changes
LGTM! Sorry for the long wait, @mberndt123. I'll merge this tomorrow unless there are further comments until then 👍

2020-05-23 16:05 UTC, mberndt123 commented
> LGTM! Sorry for the long wait, @mberndt123. I'll merge this tomorrow unless there are further comments until then +1

Awesome, thanks!

2020-05-24 09:24 UTC, jcazevedo approved these changes
LGTM

2020-05-24 09:48 UTC, merged

2020-05-24 11:18 UTC, mberndt123 commented
:partying_face: