Replace Scalariform with Scalafmt
pureconfig/pureconfig pull request #790
Opened 2020-07-03 20:27 UTC by ruippeixotog

[Scalafmt](https://github.com/scalameta/scalafmt) is more modern, more popular and better maintained than [Scalariform](https://github.com/scala-ide/scalariform). Moreover it has integration with multiple editors and IDEs. In this PR we do the plugin change and reformat all files.

I don't have strong opinions about most style settings, but I prefer to stay as close as possible to scalafmt defaults, as they're likely closer to most other projects making the code base more approachable. Therefore, I intentionally did not try to make scalafmt behave the same as scalariform. I opted to change the defaults for `align` (despite not being default it's recognized by scalafmt to be [easier for diffs](https://scalameta.org/scalafmt/docs/configuration.html#alignpresetnone)) and for `maxColumn` (no one needs 80 chars per line anymore and it actually makes code harder to read IMO). Let me know if you feel strongly for any of the other options :)

The PR is split in two commits, in case you only care about the plugin change and not about all the reformatted code.

2020-07-06 18:09 UTC, leifwickland approved these changes
Thanks for doing this. The time has come.

I'm fine with the default formatting. I'd be fine increasing the max line length to 120, but feel free to leave it as is.

Please consider adding a step to the build process which ensures that the code is formatted before any compile takes place by calling `scalafmtCheckAll` and `scalafmtSbtCheck`.

2020-07-06 21:54 UTC, ruippeixotog commented
> I'm fine with the default formatting. I'd be fine increasing the max line length to 120, but feel free to leave it as is.

Nice, I also prefer 120 :) I think @jcazevedo is ok with it too.

> Please consider adding a step to the build process which ensures that the code is formatted before any compile takes place by calling `scalafmtCheckAll` and `scalafmtSbtCheck`.

I believe we already check this in our CI indirectly - after we run all the steps (including compiling, which automatically formats files) [we run `git diff --exit-code`](https://github.com/pureconfig/pureconfig/blob/master/.github/workflows/ci.yml#L42).

This was originally intended to catch both bad formatting and outdated tut-generated files. Do you see value in having an explicit step prior to compilation that just checks formatting? While it can be clearer for users to know what went wrong, it would prevent them from seeing compilation errors in the first round (which are arguably more important).

2020-07-06 22:03 UTC, leifwickland commented
@ruippeixotog I'd forgotten we had the `git diff` check. I have a light, but easily abandoned, preference to check the formatting before compile so that the root cause of the problem is reported directly to the user, rather than requiring the user to make an inference. Feel free to leave it as is.

2020-07-07 01:01 UTC, jcazevedo requested changes

2020-07-07 01:01 UTC, jcazevedo commented on .scalafmt.conf
> +version = 2.5.2
I think we can go with 2.6.2.

2020-07-07 01:01 UTC, jcazevedo commented on core/src/main/scala/pureconfig/BasicReaders.scala
> +    ConfigReader.fromNonEmptyString[UUID](catchReadError(UUID.fromString))
Can you rerun the formatter from the original state? This line should fit in 120 chars, and there are other in the same situation.

2020-07-07 01:01 UTC, jcazevedo commented on core/src/main/scala/pureconfig/BasicReaders.scala
> +          )
I'm OK with going with the defaults, but, for the record, I'm not a fan of this style of dangling parenthesis. 😄

2020-07-07 01:01 UTC, jcazevedo commented on project/plugins.sbt
> +addSbtPlugin("org.scalameta"     % "sbt-scalafmt"    % "2.4.0")
Can you also make this change, and respective code format, in the example project?

2020-07-07 20:57 UTC, ruippeixotog commented on core/src/main/scala/pureconfig/BasicReaders.scala
> +          )
I also didn't use dangling parenthesis before, but now I like them a lot :) They make it much easier to understand the depth of each expression in a way that doesn't rely on indentation or on counting several closing parenthesis together at the end of a line.

2020-07-07 21:19 UTC, ruippeixotog commented
> @ruippeixotog I'd forgotten we had the git diff check. I have a light, but easily abandoned, preference to check the formatting before compile so that the root cause of the problem is reported directly to the user, rather than requiring the user to make an inference. Feel free to leave it as is.

I agree with providing more direct feedback to the user. My concern is on frustrating contributors by not notifying them of everything at the first chance - it's a bit annoying to have a build fail because of formatting issues, push a commit to fix it just to be notified later that a test is also failing or tut is not synced. We could have a parallel GitHub Actions job just for formatting, but it seems a bit overkill, since a job spins a full fledged Docker container (in this case three due to the matrix build).

Anyway, I added this extra step. I'll assume most sensible people compile the project before submitting a PR :)

2020-07-12 13:41 UTC, jcazevedo approved these changes

2020-07-12 14:04 UTC, merged