Screaming Snake Case naming convention
pureconfig/pureconfig pull request #915
Opened 2021-01-19 11:40 UTC by tabdulradi

2021-01-19 12:18 UTC, jcazevedo commented
I welcome this addition if it is used in the wild, as it seems to be by looking at [Wikipedia](https://en.wikipedia.org/wiki/Snake_case) and [Stack Overflow](https://stackoverflow.com/questions/11273282/whats-the-name-for-hyphen-separated-case)! I confess I didn't know about the "Screaming Snake Case" term nor have found uses of it in Scala projects yet.

Thanks @tabdulradi!

2021-01-19 14:26 UTC, leifwickland commented
@jcazevedo I'm not sure that I've heard anyone use the term within the Scala community, but I am familiar with the term from other contexts.

I'm disappointed to report that I have needed this convention in the past to match the style from a project in another language.

I favor adding this feature.

2021-01-19 14:28 UTC, leifwickland commented
@tabdulradi,

Thanks for the contribution.

Please add the new convention to the [list of conventions in the documentation](https://github.com/pureconfig/pureconfig/blame/master/docs/docs/docs/overriding-behavior-for-case-classes.md#L64)

2021-01-19 14:45 UTC, ruippeixotog commented
I haven't heard that term before either, but I'm not surprised there's a name for it and I'm actually surprised that this feature request didn't come up earlier, given that Typesafe Config injects env vars in configs 🙂

2021-01-20 23:47 UTC, ruippeixotog requested changes
LGTM! Just a nit below.

2021-01-20 23:47 UTC, ruippeixotog commented on docs/docs/docs/overriding-behavior-for-case-classes.md
> +* ScreamingSnakeCase (examples: `SCREAMING_SNAKE_CASE`, `USE_MORE_PURECONFIG`);
nit: can you make this monospace and link to https://en.wikipedia.org/wiki/Snake_case? I think it's still useful to link to it even if it's only mentioned in the History section.

```suggestion
* [`ScreamingSnakeCase`](https://en.wikipedia.org/wiki/Snake_case) (examples: `SCREAMING_SNAKE_CASE`, `USE_MORE_PURECONFIG`);
```

2021-01-22 13:24 UTC, ruippeixotog approved these changes

2021-01-22 13:25 UTC, merged

2021-01-22 13:25 UTC, ruippeixotog commented
Thanks!